### PR TITLE
The big merge

### PR DESCRIPTION
**Pull request by pablisco**
Need to merge the extraction of the utils (#11). This PR merges `@Transformative` and `@MutableCopy`. Along with a few other small tweaks.

### CODE REVIEW

**Comment by serras** [comment]
Thanks for the awesome work you’re putting on this! 

I’m thinking that maybe we should remove the annotations altogether, by including the plug-in you are already saying that you want to create the methods, and they can be applied to any data class (as opposed to, say, `@Serializable`). This has the added benefit that there’s no extra `types` module to depend on, because KSP is completely compile-time.

**Comment by pablisco** [comment]
> Thanks for the awesome work you’re putting on this!
> 
> I’m thinking that maybe we should remove the annotations altogether, by including the plug-in you are already saying that you want to create the methods, and they can be applied to any data class (as opposed to, say, @serializable). This has the added benefit that there’s no extra `types` module to depend on, because KSP is completely compile-time.

I managed to figure out how to do that here. 7f068ab I'm scared by the amount of power that this gives us :exploding\_head:

**Comment by serras** [comment]
I was just working on the very same thing at the very same moment. I think that we should add an option for disabling the generators if any of them is not desired, as I did in https://github.com/pablisco/transformative/pull/1/commits/17105d562b1f5f01ff606487836757ec052b7814

**Comment by pablisco** [comment]
That sounds good :+1:  I'll add that. I'm also inlining the copy and transform functions :see\_no\_evil:

**Comment by pablisco** [comment]
> I was just working on the very same thing at the very same moment. I think that we should add an option for disabling the generators if any of them is not desired, as I did in pablisco/transformative@17105d5

Done here: 3fa087e Thanks for the suggestion

**Pull request merged**
